name: Release
concurrency: ci-${{ github.ref }}
on:
    workflow_dispatch:
jobs:
    build:
        runs-on: ubuntu-22.04
        steps:
            - name: Setup Java
              run: |
                  echo "JAVA_HOME=$JAVA_HOME_17_X64" >> "$GITHUB_ENV"
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - uses: fregante/setup-git-user@v2
            - uses: gradle/gradle-build-action@v2
              name: Setup Gradle
              with:
                  cache-read-only: ${{ !startsWith(github.ref, 'refs/heads/1.') }}
            - name: Tag Release
              run: ./gradlew tagRelease --configuration-cache
            - name: Build
              run: ./gradlew build --configuration-cache
            - name: Publish
              run: ./gradlew publishPlugins --configuration-cache
              env:
                GRADLE_PLUGIN_KEY: ${{ secrets.GRADLE_PLUGIN_KEY }}
                GRADLE_PLUGIN_SECRET: ${{ secrets.GRADLE_PLUGIN_SECRET }}
            - name: Push Changes
              run: |
                git push
                git push --tags
